devel

diff --git a/etc/init.d/storm-frontend.in b/etc/init.d/storm-frontend.in
--- a/etc/init.d/storm-frontend.in
+++ b/etc/init.d/storm-frontend.in
@@ -18,6 +18,8 @@ CONFIGURATION_FILE=@PREFIX@/etc/storm-frontend.conf
 
 case "$1" in
   start)
+    echo "Starting $prog... "
+
     # Script must be launched as root
     if [ ! `whoami` = "root" ]; then
         echo "Error: you must be root."
@@ -29,7 +31,21 @@ case "$1" in
         echo "Found lock file ($LOCKFILE). StoRM frontend already running."
         exit 1
     fi
-    echo -n "Starting $prog... "
+
+    # Check for the configuration file
+    if [ ! -f $CONFIGURATION_FILE ]; then
+        echo "Configuration file not found: $CONFIGURATION_FILE"
+        exit 1
+    fi
+
+    FE_USER=` cat $CONFIGURATION_FILE | grep "fe.user" | awk -F"=" '{gsub( /[ \t]+/, "" ); print $2}'`
+
+    mkdir -p @PREFIX@/var
+    chown -R $FE_USER @PREFIX@/* > /dev/null
+    if [ ! $? -eq 0 ]; then
+        echo "Error: invalid user \'$FE_USER\'"
+        exit 1
+    fi
 
     # Launch the frontend
     $FRONTEND_DAEMON -c $CONFIGURATION_FILE
@@ -40,9 +56,9 @@ case "$1" in
         rm -f $PIDFILE
         echo $pid > $PIDFILE
         RETVAL=0
-        echo "ok"
+        echo "$prog started."
     else
-        echo "error ($prog not started)"
+        echo "Error: $prog not started."
         RETVAL=1
     fi
     ;;
